name: /home/edisel/DEV/SportLizn/ShFEM/SoftFem
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - anyio=4.12.0
  - app-model=0.4.0
  - appdirs=1.4.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asciitree=0.3.3
  - assimp=5.4.3
  - asttokens=3.0.1
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attr=2.5.2
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.3
  - bermuda=0.1.6
  - binutils_impl_linux-64=2.45
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blinker=1.9.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachey=0.2.1
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cli11=2.6.0
  - click=8.3.1
  - cloudpickle=3.1.2
  - cmake=4.2.0
  - colorama=0.4.6
  - comm=0.2.3
  - conda-gcc-specs=15.2.0
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dash=3.3.0
  - dask-core=2025.11.0
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docstring_parser=0.17.0
  - docutils=0.21.2
  - double-conversion=3.3.1
  - eigen=3.4.0
  - embree=4.4.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - f2c=20210323183018
  - fasteners=0.19
  - fftw=3.3.10
  - flask=3.1.2
  - flexcache=0.3
  - flexparser=0.4
  - fmt=11.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - freetype-py=2.5.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gcc=15.2.0
  - gcc_impl_linux-64=15.2.0
  - gdcm=2.8.9
  - gl2ps=1.4.2
  - glew=2.2.0
  - glfw=3.4
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - heapdict=1.0.1
  - hpack=4.1.0
  - hsluv=5.0.4
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imageio=2.37.0
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - in-n-out=0.2.1
  - intel-openmp=2025.0.0
  - ipykernel=6.31.0
  - ipython=8.37.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.17
  - json5=0.12.1
  - jsoncpp=1.9.6
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.6
  - libclang13=21.1.6
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libitk=5.4.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm20=20.1.8
  - libllvm21=21.1.6
  - liblzf=3.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopengl-devel=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.51
  - libpq=18.1
  - libsanitizer=15.2.0
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.1.1
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - llvmlite=0.45.1
  - locket=1.0.0
  - loguru=0.7.3
  - lz4-c=1.10.0
  - magicgui=0.10.1
  - make=4.4.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mesalib=25.0.5
  - mistune=3.1.4
  - mkl=2025.2.0
  - mkl-devel=2025.2.0
  - mkl-include=2025.2.0
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - munkres=1.1.4
  - napari=0.6.6
  - napari-base=0.6.6
  - napari-console=0.1.4
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.8
  - napari-svg=0.2.1
  - narwhals=2.13.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - npe2=0.7.9
  - numba=0.62.1
  - numcodecs=0.13.1
  - numpy=2.2.6
  - numpydoc=1.9.0
  - open3d=0.19.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - partsegcore-compiled-backend=0.15.14
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pint=0.24.4
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.5.0
  - pooch=1.8.2
  - proj=9.7.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.3
  - psygnal=0.15.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pyconify=0.2.1
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-compat=0.1.2
  - pydantic-core=2.41.5
  - pydicom=3.0.1
  - pygments=2.19.2
  - pyopengl=3.1.10
  - pyparsing=3.2.5
  - pyproject_hooks=1.2.0
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.10.12
  - python-build=1.3.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyvista=0.46.4
  - pywavelets=1.8.0
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - qtconsole-base=5.7.0
  - qtpy=2.4.3
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - retrying=1.4.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rhash=1.4.6
  - rich=14.2.0
  - rpds-py=0.30.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - scooby=0.11.0
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simpleitk=2.5.3
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.8
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spirv-tools=2025.4
  - sqlite=3.51.0
  - stack_data=0.6.3
  - superqt=0.7.6
  - sysroot_linux-64=2.39
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2025.2.18
  - tinycss2=1.5.1
  - tinyobjloader=1.0.7
  - tk=8.6.15
  - tomli=2.3.0
  - tomli-w=1.2.0
  - toolz=1.1.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - utfcpp=4.0.8
  - vispy=0.15.2
  - vtk-base=9.5.1
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - werkzeug=3.1.4
  - wheel=0.45.1
  - wrapt=2.0.1
  - wslink=2.5.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.22.0
  - zarr=2.18.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - pyrmifeem==0.1.0
      - python-gdcm==3.2.2
prefix: /home/edisel/DEV/SportLizn/ShFEM/SoftFem
